image: python:3.4-alpine

pages:
  script:
  - apk update && apk add doxygen
  - pip install sphinx
  - pip install sphinx_bootstrap_theme
  - cd doc/doxygen
  - doxygen Doxyfile
  - mv html/ ../../public/
  artifacts:
    paths:
    - public
  only:
  - master