image: pagmo/ubuntu:v1

# pagmo-gcc:
#   script:
#     - apk add bash
#     - mkdir build
#     - cd build
#     - cmake -DCMAKE_CXX_FLAGS=--coverage -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_TUTORIALS=ON ..
#     - make -j4
#     - make test
#     - wget https://codecov.io/bash -O codecov.sh
#     - bash codecov.sh -t ca222632-02f3-4603-b2d6-7e1b3d3149e4
#
# pagmo-clang:
#   script:
#     - mkdir build
#     - cd build
#     - CXX=clang++ CC=clang cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_TUTORIALS=ON -DBoost_UNIT_TEST_FRAMEWORK_LIBRARY_DEBUG=/home/pagmo/libboost_unit_test_framework.so ..
#     - make -j4
#     - make test

pygmo-clang:
  script:
    - mkdir build
    - cd build
    - CXX=clang++ CC=clang cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_PYGMO=ON -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON_EXECUTABLE=/usr/bin/python3 -DBoost_PYTHON_LIBRARY_DEBUG=/usr/lib/x86_64-linux-gnu/libboost_python-py35.so  ..
    - make -j4
    - make install

# pages:
#   script:
#   - cd doc/sphinx
#   - ./compile.sh
#   - mv _build/html ../../public/
#   artifacts:
#     paths:
#     - public
#   only:
#   - master
