image: python:3.4-alpine

pages:
  script:
  - apk update && apk add doxygen
  - pip install sphinx
  - pip install sphinx_bootstrap_theme
  - pip install breathe
  - cd doc/doxygen
  - doxygen Doxyfile
  - cd ../sphinx
  - make html
  - mv _build/html ../../public/
  artifacts:
    paths:
    - public
  only:
  - master