image: pagmo/ci-alpine:v1

pagmo-gcc:
  script:
    - apk add bash
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_FLAGS=--coverage -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_TUTORIALS=ON ..
    - make -j4
    - make test
    - wget https://codecov.io/bash
    - bash bash

pagmo-clang:
  script:
    - mkdir build
    - cd build
    - CXX=clang++ CC=clang cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_TUTORIALS=ON -DBoost_UNIT_TEST_FRAMEWORK_LIBRARY_DEBUG=/home/pagmo/libboost_unit_test_framework.so ..
    - make
    - make test

pages:
  script:
  - cd doc/sphinx
  - ./compile.sh
  - mv _build/html ../../public/
  artifacts:
    paths:
    - public
  only:
  - master
