image: pagmo/ci-alpine:v1

pagmo-gcc:
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_TUTORIALS=ON ..
    - make
    - make test

pagmo-clang:
  script:
    - mkdir build
    - cd build
    - CXX=clang++ CC=clang cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_TUTORIALS=ON ..
    - make
    - make test

pages:
  script:
  - cd doc/doxygen
  - doxygen Doxyfile
  - cd ../sphinx
  - make html
  - mv _build/html ../../public/
  artifacts:
    paths:
    - public
  only:
  - master
