image: alpine

pages:
  script:
  - apk update && apk add doxygen
  - doxygen doc/doxygen/Doxyfile
  - mv doc/doxygen/documentation/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master